import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>React R&D</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>React R&D</h1>
        <ul>
          <li>
            <Link href="/research/convKana">
              <a>入力値をカタカナに変換</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  )
}

export default Home
